name: 🔂 Surge PR Preview

on: [pull_request]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # allow surge-preview to create/update PR comments
    steps:
      - uses: actions/checkout@v2
      # Yes, we really want to checkout the PR
      - run: |
          if [[ ! -z "${GH_PR_NUM}" ]]; then 
            echo "Checking out PR"
            git fetch origin pull/$GH_PR_NUM/head:tmp
            git checkout tmp
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v2
        id: yarn-cache
        name: Cache npm deps
        with:
          path: |
           node_modules
           **/node_modules
           ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-14-${{ secrets.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - uses: actions/cache@v2
        id: dist
        name: Cache dist
        with:
          path: |
            packages/*/dist
            packages/react-styles/css
          key: ${{ runner.os }}-dist-14-${{ secrets.CACHE_VERSION }}-${{ hashFiles('yarn.lock', 'package.json', 'packages/*/*', '!packages/*/dist', '!packages/*/node_modules') }}
      - name: Build dist
        run: yarn build
        if: steps.dist.outputs.cache-hit != 'true'
      - name: Build docs
        run: yarn build:docs
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        id: preview_step
        with:
          node-version: '16'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          surge_token: ${{ secrets.SURGE_TOKEN }}
          dist: packages/module/public
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"