name: 🔂 Surge PR Preview

on: [pull_request]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # allow surge-preview to create/update PR comments
    steps:
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          dist: packages/module/public
          build: |
            yarn install
            yarn run build
            yarn run build:docs
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"